# Generated by Django 5.1.6 on 2025-02-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopapp', '0007_categorydb_productdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdb',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ice_stock',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.DeleteModel(
            name='CategoryDb',
        ),
        migrations.DeleteModel(
            name='ProductDb',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='IceStock',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
