# Generated by Django 5.1.6 on 2025-02-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopapp', '0011_order_orderitem_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ice_stock',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='IceStock',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
