# Generated by Django 5.1.6 on 2025-03-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopapp', '0017_shopowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdb',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
