# Generated by Django 5.1.6 on 2025-03-20 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopapp', '0018_categorydb_is_approved_productdb_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydb',
            name='shop_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shopapp.shopowner'),
        ),
        migrations.AddField(
            model_name='productdb',
            name='shop_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shopapp.shopowner'),
        ),
    ]
