# Generated by Django 5.1.6 on 2025-02-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iceapp', '0002_registerdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterDb',
        ),
    ]
