# Generated by Django 5.1.6 on 2025-03-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iceapp', '0004_customer_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ice_stock',
        ),
    ]
