# Generated by Django 5.1.6 on 2025-03-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iceapp', '0005_remove_order_customer_remove_order_ice_stock'),
        ('Shopapp', '0015_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
