# Generated by Django 5.1.6 on 2025-03-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iceapp', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutdb',
            name='Total_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkoutdb',
            name='productname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
