# Generated by Django 5.1.6 on 2025-03-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iceapp', '0008_checkoutdb_total_price_checkoutdb_productname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkoutdb',
        ),
    ]
