# Generated by Django 5.1.6 on 2025-03-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iceapp', '0010_checkoutdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkoutdb',
        ),
    ]
