# Generated by Django 5.1.6 on 2025-03-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iceapp', '0012_checkoutdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
